### PR TITLE
prepare for adding new Salimans paper (wip)

### PR DESCRIPTION
**Pull request by lucidrains**
- [x] build out inner vit
- [x] only dropout at vit stage
- [x] complete their approach to noising of high resolutions, which is vastly different than Ting Chen's
- [x] add v-prediction, for completeness sake
- [x] add patching method by setting `patch_size` on UViT
- [x] be able to finely specify what factor to downsample at for any given stage (they go for 4x downsampling in their work)
- [ ] add dwt

will test on <a href="https://github.com/lucidrains/lightweight-gan">512x512 pizza</a> before merging, or if someone else trains 512x512 successfully

https://arxiv.org/abs/2301.11093v1

### CODE REVIEW

**Comment by lucidrains** [comment]
there's really just 4 bullet points

1. more noise for higher resolution images, concurrently explored by [Ting Chen](https://arxiv.org/abs/2301.10972)
2. big transformer at the lowest resolution of the unet, they scaled up to 30 layers here
3. downsample immediately, using either patches or DWT (dwt apparently gave best results)
4. only use dropout at transformer stage

**Comment by lucidrains** [comment]
if anyone spots anything else in the paper that is worth mentioning, drop a line

**Comment by lucidrains** [comment]
maybe just use this for DWT https://pytorch-wavelets.readthedocs.io/en/latest/dwt.html

**Comment by tcapelle** [comment]
Looking on my phone but I think they use swish over silu?

**Pull request merged**
