### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kaanaksit**
Minor typo.

### CODE REVIEW

**Comment by lucidrains** [comment]
Hey Kaan

It should be 0 to 1, as I normalize (and unnormalize during sampling) it to -1 to 1 [here](https://github.com/lucidrains/denoising-diffusion-pytorch/blob/main/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L709)

**Comment by kaanaksit** [comment]
hey luciddrains,

I believe 'torch.randn' generates zero mean random numbers, no?

**Comment by lucidrains** [comment]
@kaanaksit haha yea, but it is just for testing, not real image data

i see why you are confused though

**Comment by lucidrains** [comment]
https://github.com/lucidrains/denoising-diffusion-pytorch/commit/e872ec361881dc74cfda48e3d76ff0148b63e1f4

**Comment by kaanaksit** [comment]
Perhaps removing the comment may help your readers . Btw, thank you for making this code base available, huge help to folks out there!

**Comment by kaanaksit** [comment]
Closing the pull request

**Pull request closed without merging**
